sb_activity_activity:
    resource: "@SBActivityBundle/Resources/config/routes/activity.yml"
    prefix:   /

sb_activity_likes:
    resource: "@SBActivityBundle/Resources/config/routes/likes.yml"
    prefix:   /

sb_activity_comments:
    resource: "@SBActivityBundle/Resources/config/routes/comments.yml"
    prefix:   /
