sb_activity_add:
    path:     /ajouter-une-activite/
    methods: [POST]
    defaults: { _controller: SBActivityBundle:Activity:addActivity }

sb_activity_profil_add:
    path:     /ajouter-une-activite-depuis-mon-profil/
    methods: [POST]
    defaults: { _controller: SBActivityBundle:Activity:addActivityOnProfil }

sb_activity_like:
    path:     /ajouter-un-like/
    methods: [POST]
    options:
        expose: true
    defaults: { _controller: SBActivityBundle:Activity:addLike }

sb_activity_dislike:
    path:     /supprimer-un-like/
    methods: [POST]
    options:
        expose: true
    defaults: { _controller: SBActivityBundle:Activity:dislike }

sb_activity_get_comments:
    path:     /obtenir-les-commentaires/
    methods: [POST]
    options:
        expose: true
    defaults: { _controller: SBActivityBundle:Activity:activityGetComment }

sb_activity_add_comment:
    path:     /ajouter-un-commentaire/
    methods: [POST]
    options:
        expose: true
    defaults: { _controller: SBActivityBundle:Activity:addComment }

sb_activity_get_activity:
    path:     /obtenir-des-activites/
    methods: [POST]
    options:
        expose: true
    defaults: { _controller: SBActivityBundle:Activity:getActivity }

sb_activity_get_my_activity:
    path:     /obtenir-mes-activites/
    methods: [POST]
    options:
        expose: true
    defaults: { _controller: SBActivityBundle:Activity:getMyActivity }
