sb_activity_add:
    path:     /ajouter-une-activite/
    methods: [POST]
    defaults: { _controller: SBActivityBundle:Activity:activityAdd }

sb_activity_like:
    path:     /ajouter-un-like/
    methods: [POST]
    options:
        expose: true
    defaults: { _controller: SBActivityBundle:Activity:activityLike }

sb_activity_dislike:
    path:     /supprimer-un-like/
    methods: [POST]
    options:
        expose: true
    defaults: { _controller: SBActivityBundle:Activity:activityDislike }

sb_activity_get_comments:
    path:     /obtenir-les-commentaires/
    methods: [POST]
    options:
        expose: true
    defaults: { _controller: SBActivityBundle:Activity:activityGetComment }

sb_activity_add_comment:
    path:     /ajouter-un-commentaire/
    methods: [POST]
    options:
        expose: true
    defaults: { _controller: SBActivityBundle:Activity:activityComment }

sb_activity_get_activity:
    path:     /obtenir-des-activites/
    methods: [POST]
    options:
        expose: true
    defaults: { _controller: SBActivityBundle:Activity:activityGet }

sb_activity_get_my_activity:
    path:     /obtenir-mes-activites/
    methods: [POST]
    options:
        expose: true
    defaults: { _controller: SBActivityBundle:Activity:activityGetMy }
