<?php

namespace SB\Bundle\UserBundle\Repository;

/**
 * ConfidentialityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfidentialityRepository extends \Doctrine\ORM\EntityRepository
{
}
