rules:
    composer.warning:
        enabled: false
    twig.twig_syntax_error:
        enabled: false
    symfony.dependency_injection.no_container_as_parameter:
        enabled: false

global_exclude_dirs:
    - src/SB/Bundle/ActivityBundle/Resources/views/Utils
    - src/SB/Bundle/NotificationBundle/Resources/views/Utils
    - src/SB/Bundle/UserBundle/Resources/views/Utils

