<?php

namespace SB\ActivityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends EntityRepository
{
    public function fetchAll($id_user)
    {
        $qb = $this->createQueryBuilder('a');

        $qb
            ->join('a.user', 'user')
            ->where('a.user = :id_user')
            ->setParameter('id_user', $id_user)
        ;

        return $qb->getQuery()->getResult();
    }
}
