<?php

namespace SB\ActivityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends EntityRepository
{
    public function fetchAll($id_user, array $list_friends, $limit)
    {
        $qb = $this->createQueryBuilder('a');

        $qb
            ->where('a.user = :id_user')
        ;
        if (!empty($list_friends)) {
            foreach ($list_friends as $key => $friend) {
                $qb
                    ->orWhere('a.user = :friend' . $key)
                        ->setParameter('friend' . $key, $friend->getId())
                ;
            }
        }
        $qb
            ->leftJoin('a.image', 'i')
                ->addSelect('i')
            ->leftJoin('a.likes', 'l', 'WITH', 'l.user = :id_user')
                ->addSelect('l')
            ->setParameter('id_user', $id_user)
            ->orderBy('a.dateActivity', 'DESC')
            ->setMaxResults($limit)
        ;

        return $qb->getQuery()->getResult();
    }
}
