sb_admin:
    resource: "@SBAdminBundle/Resources/config/routing.yml"
    prefix:   /administration

sb_activity:
    resource: "@SBActivityBundle/Resources/config/routing.yml"
    prefix:   /

sb_core:
    resource: "@SBCoreBundle/Resources/config/routing.yml"
    prefix:   /

sb_user:
    resource: "@SBUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
