sb_activity:
    resource: "@SBActivityBundle/Resources/config/routing.yml"
    prefix:   /

sb_core:
    resource: "@SBCoreBundle/Resources/config/routing.yml"
    prefix:   /

login:
    path:   /connexion
    defaults:  { _controller: SBUserBundle:Security:login }

login_check:
    path:   /login_check

logout:
    path:   /deconnexion

user_registration:
    path:     /inscription
    defaults: { _controller: SBUserBundle:Registration:register }

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
