sb_core:
    resource: "@SBCoreBundle/Resources/config/routing.yml"
    prefix:   /

login:
    pattern:   /connexion
    defaults:  { _controller: SBUserBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /deconnexion

user_registration:
    path:     /inscription
    defaults: { _controller: SBUserBundle:Registration:register }
