parameters:
    sb_realtime.faye.endpoint:      'http://localhost:3000/'
    sb_realtime.faye.adapter.class: 'Nc\FayeClient\Adapter\CurlAdapter'
    sb_realtime.faye.client.class:  'Nc\FayeClient\Client'

services:
    sb_realtime.faye.adapter:
        class:     '%sb_realtime.faye.adapter.class%'
    sb_realtime.faye.client:
        class:     '%sb_realtime.faye.client.class%'
        arguments:
            - '@sb_realtime.faye.adapter'
            - '%sb_realtime.faye.endpoint%'
    app.twig_extension:
        class: SB\Bundle\CoreBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }