<?php

namespace SB\Bundle\ActivityBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    public function fetchAll($id_activity, $limit)
    {
        $qb = $this->createQueryBuilder('c');

        $qb
            ->where('c.activity = :id_activity')
                ->setParameter('id_activity', $id_activity)
            ->join('c.user', 'u')
                ->addSelect('u')
            ->orderBy('c.dateComment', 'ASC')
            ->setMaxResults($limit)
        ;

        return $qb->getQuery()->getResult();
    }

    public function countAll($id_activity)
    {
        $qb = $this->createQueryBuilder('c');

        $qb
            ->select('COUNT(c)')
            ->where('c.activity = :id_activity')
                ->setParameter('id_activity', $id_activity)
        ;

        return $qb->getQuery()->getSingleScalarResult();
    }
}
