<?php

namespace SB\Bundle\ActivityBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LikesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LikesRepository extends EntityRepository
{
}
