user_registration:
    path:     /inscription
    methods: [GET, POST]
    defaults: { _controller: SBUserBundle:Registration:register }

login:
    path:   /connexion
    methods: [GET, POST]
    defaults:  { _controller: SBUserBundle:Security:login }

login_check:
    path:   /login_check

logout:
    path:   /deconnexion

sb_user_profil_update_profil:
    path:     /modifier-mon-profil
    methods: [POST]
    options:
        expose: true
    defaults: { _controller: SBUserBundle:Profil:updateProfil }

sb_user_profil_update_profil_confidentiality:
    path:     /modifier-mes-paramètres-de-confidentialite
    methods: [POST]
    options:
        expose: true
    defaults: { _controller: SBUserBundle:Profil:updateProfilConfidentiality }

sb_user_profil_update_profil_avatar:
    path:     /modifier-mon-avatar
    methods: [POST]
    options:
        expose: true
    defaults: { _controller: SBUserBundle:Profil:updateProfilAvatar }

sb_user_profil:
    path:     /{slugUsername}
    methods: [GET]
    defaults: { _controller: SBUserBundle:Profil:profil }
