user_registration:
    path:     /inscription
    defaults: { _controller: SBUserBundle:Registration:register }

login:
    path:   /connexion
    defaults:  { _controller: SBUserBundle:Security:login }

login_check:
    path:   /login_check

logout:
    path:   /deconnexion

sb_user_profil_update_profil:
    path:     /modifier-mon-profil
    methods: [POST]
    options:
        expose: true
    defaults: { _controller: SBUserBundle:Profil:updateProfil }

sb_user_profil:
    path:     /{slugUsername}
    methods: [GET]
    defaults: { _controller: SBUserBundle:Profil:profil }
