sb_core_homepage:
    path:     /
    methods: [GET]
    options:
        expose: true
    defaults: { _controller: SBCoreBundle:Core:index }

sb_core_feedback_add:
    path:     /add-feedback/
    methods: [POST]
    options:
        expose: true
    defaults: { _controller: SBCoreBundle:Feedback:add }
