services:
    app.twig_extension:
        class: SB\Bundle\CoreBundle\Twig\AppExtension
        public: true
        tags:
            -  { name: twig.extension }
    twig.extension.actions:
        class: SB\Bundle\CoreBundle\Twig\NullExtension
