services:
    app.twig_extension:
        class: SB\Bundle\CoreBundle\Twig\AppExtension
        public: true
        tags:
            -  { name: twig.extension }
    sb_app.app_function:
        class: SB\Bundle\CoreBundle\Utils\SBApp
